version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    env_file:
      - apps/cheap-baltimore-houses/.env
    ports:
      - 1337:1337
    image: cbhregistry.azurecr.io/api:latest
  nextjs:
    depends_on:
      - api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://api:1337
    image: cbhregistry.azurecr.io/nextjs:latest
  nginx:
    depends_on:
      - nextjs
      - api
    build: ./nginx
    ports:
      - 80:80
    image: cbhregistry.azurecr.io/nginx:latest