version: '3'
services:
  api:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.api
    env_file:
      - apps/cheap-baltimore-houses/.env
    ports:
      - 1337:1337
    image: cheapbmorehousesregistry.azurecr.io/api:latest
    restart: always

  nextjs:
    depends_on:
      - api
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://api:1337
      - API_URL=http://api:1337
      - NEXT_SHARP_PATH=/tmp/node_modules/sharp
    image: cheapbmorehousesregistry.azurecr.io/nextjs:latest
    restart: always

  nginx:
    depends_on:
      - nextjs
      - api
    platform: linux/amd64
    build: ./nginx
    ports:
      - 80:80
    image: cheapbmorehousesregistry.azurecr.io/nginx:latest