version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - 1337:1337
    platform: linux/amd64
  nextjs:
    depends_on:
      - api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://api:1337
    platform: linux/amd64
  nginx:
    build: ./nginx
    ports:
      - 80:80
    platform: linux/amd64