services:
  - type: web
    name: cbh-api
    env: node

    plan: free
    region: ohio
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: cbh-api-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16.14
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cbh-api
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: cbh-api
    plan: starter
