name: Code Quality
on:
  pull_request:
  push:
    branches:
      - development

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write /home/runner/work/cheap-baltimore-houses/cheap-baltimore-houses/apps/**/*.{js,jsx,ts,tsx} --check --config ./.prettierrc
          only_changed: True
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
    permissions:
      checks: write
      contents: write

  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
