name: Code Quality
on:
  pull_request:
  push:
    branches:
      - development

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [client, cheap-baltimore-houses]
    steps:
      - uses: actions/checkout@v3
      - name: Check Code Style
        uses: ./.github/actions/code-style
        with:
          app: ${{ matrix.app }}

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn workspace client install
      - name: Lint
        run: yarn lint
