name: Code Quality
on:
  pull_request:
  push:
    branches:
      - development

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: List directory contents
        run: ls -R
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write /home/runner/work/cheap-baltimore-houses/cheap-baltimore-houses/apps/client/**/*.{js,jsx,ts,tsx} --check --config ./.prettierrc
          only_changed: True
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
