name: Deploy To Production
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      app_name:
        type: choice
        description: "App Name"
        required: true
        options:
          - api
          - nextjs
          - nginx
          - all
        default: "nextjs"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment status
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Checkout
        uses: actions/checkout@v3

      - name: Begin deployment
        uses: ./.github/actions/deploy
        with:
          app: ${{ github.event.inputs.app_name }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
