name: "Pull Request Labeler"
on:
  pull_request_target:
    branches:
      - development

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered"
      - uses: actions/labeler@v4
