name: Unit Tests CI
on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn client:test
