/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/home.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box.geometry}
        material={nodes.box.material}
        position={[-13.5, -21.06, -6]}
        rotation={[0, 0, -Math.PI]}
        scale={[-3, 0.25, 1.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_1.geometry}
        material={nodes.box_1.material}
        position={[-13.5, -19.56, -5]}
        scale={[3, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_2.geometry}
        material={nodes.box_2.material}
        position={[0, -20.5, -26.5]}
        scale={[12.75, 0.5, 10.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_3.geometry}
        material={nodes.box_3.material}
        position={[29.5, -34.62, -25.5]}
        scale={[0.25, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_4.geometry}
        material={nodes.box_4.material}
        position={[29.5, -36.12, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_5.geometry}
        material={nodes.box_5.material}
        position={[29.5, -36.12, -30.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_6.geometry}
        material={nodes.box_6.material}
        position={[29.5, -36.12, -25.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_7.geometry}
        material={nodes.box_7.material}
        position={[29.5, -36.12, -20.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_8.geometry}
        material={nodes.box_8.material}
        position={[29.5, -36.12, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_9.geometry}
        material={nodes.box_9.material}
        position={[26.5, -37.62, -25.5]}
        scale={[1.75, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_10.geometry}
        material={nodes.box_10.material}
        position={[26.5, -34.62, -34.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_11.geometry}
        material={nodes.box_11.material}
        position={[24.5, -36.12, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_12.geometry}
        material={nodes.box_12.material}
        position={[26.5, -34.62, -16.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_13.geometry}
        material={nodes.box_13.material}
        position={[24.5, -36.12, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_18.geometry}
        material={nodes.box_18.material}
        position={[26.5, -15.62, -25.5]}
        scale={[1.75, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_19.geometry}
        material={nodes.box_19.material}
        position={[24.5, -14.12, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_20.geometry}
        material={nodes.box_20.material}
        position={[29.5, -14.12, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_21.geometry}
        material={nodes.box_21.material}
        position={[29.5, -14.12, -20.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_22.geometry}
        material={nodes.box_22.material}
        position={[29.5, -12.62, -25.5]}
        scale={[0.25, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_23.geometry}
        material={nodes.box_23.material}
        position={[29.5, -14.12, -25.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_24.geometry}
        material={nodes.box_24.material}
        position={[29.5, -14.12, -30.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_25.geometry}
        material={nodes.box_25.material}
        position={[29.5, -14.12, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_26.geometry}
        material={nodes.box_26.material}
        position={[26.5, -12.62, -34.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_27.geometry}
        material={nodes.box_27.material}
        position={[24.5, -14.12, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_37.geometry}
        material={nodes.box_37.material}
        position={[26.5, 4.5, -16.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_38.geometry}
        material={nodes.box_38.material}
        position={[29.5, 3, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_39.geometry}
        material={nodes.box_39.material}
        position={[29.5, 3, -20.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_40.geometry}
        material={nodes.box_40.material}
        position={[26.5, 1.5, -25.5]}
        scale={[1.75, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_41.geometry}
        material={nodes.box_41.material}
        position={[29.5, 4.5, -25.5]}
        scale={[0.25, 0.25, 4.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_42.geometry}
        material={nodes.box_42.material}
        position={[29.5, 3, -25.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_43.geometry}
        material={nodes.box_43.material}
        position={[29.5, 3, -30.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_44.geometry}
        material={nodes.box_44.material}
        position={[29.5, 3, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_45.geometry}
        material={nodes.box_45.material}
        position={[26.5, 4.5, -34.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_46.geometry}
        material={nodes.box_46.material}
        position={[24.5, 3, -34.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_50.geometry}
        material={nodes.box_50.material}
        position={[26.5, -12.62, -16.5]}
        scale={[1.75, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_53.geometry}
        material={nodes.box_53.material}
        position={[24.5, 3, -16.5]}
        scale={[0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_54.geometry}
        material={nodes.box_54.material}
        position={[0, 33.5, -11]}
        scale={[6.25, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_55.geometry}
        material={nodes.box_55.material}
        position={[0, 40.5, -11]}
        scale={[6.25, 0.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_56.geometry}
        material={nodes.box_56.material}
        position={[-12, 32.5, -11]}
        scale={[0.25, 4.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_57.geometry}
        material={nodes.box_57.material}
        position={[12, 32.5, -11]}
        scale={[0.25, 4.25, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_140.geometry}
        material={nodes.box_140.material}
        position={[0, -46.06, -26.5]}
        scale={[11.75, 0.75, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_141.geometry}
        material={nodes.box_141.material}
        position={[0, -46.06, 8]}
        scale={[35.25, 0.75, 7.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_142.geometry}
        material={nodes.box_142.material}
        position={[0, -47.06, 38.5]}
        scale={[35.25, 0.25, 8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_143.geometry}
        material={nodes.box_143.material}
        position={[67.5, -45.56, 21]}
        scale={[1.5, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_144.geometry}
        material={nodes.box_144.material}
        position={[47, -46.56, -30.5]}
        scale={[11.75, 0.5, 12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_145.geometry}
        material={nodes.box_145.material}
        position={[0, -46.56, -50.5]}
        scale={[11.75, 0.5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_146.geometry}
        material={nodes.box_146.material}
        position={[-38.5, -45.56, -7.5]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_147.geometry}
        material={nodes.box_147.material}
        position={[-28.5, -45.56, -7.5]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_148.geometry}
        material={nodes.box_148.material}
        position={[67, -45.56, -7.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.75, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_149.geometry}
        material={nodes.box_149.material}
        position={[28.5, -45.5, -7.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_150.geometry}
        material={nodes.box_150.material}
        position={[38.5, -45.5, -7.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_151.geometry}
        material={nodes.box_151.material}
        position={[48.5, -45.5, -7.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_152.geometry}
        material={nodes.box_152.material}
        position={[58.5, -45.5, -7.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_176.geometry}
        material={nodes.box_176.material}
        position={[-67, -45.56, -7.5]}
        scale={[1.75, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_219.geometry}
        material={nodes.box_219.material}
        position={[-48.5, -45.56, -7.5]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_220.geometry}
        material={nodes.box_220.material}
        position={[-58.5, -45.56, -7.5]}
        scale={[2.5, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_226.geometry}
        material={nodes.box_226.material}
        position={[-63, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_227.geometry}
        material={nodes.box_227.material}
        position={[-48, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_228.geometry}
        material={nodes.box_228.material}
        position={[-33, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_229.geometry}
        material={nodes.box_229.material}
        position={[-18, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_230.geometry}
        material={nodes.box_230.material}
        position={[-3, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_231.geometry}
        material={nodes.box_231.material}
        position={[12, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_232.geometry}
        material={nodes.box_232.material}
        position={[57, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_233.geometry}
        material={nodes.box_233.material}
        position={[27, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_234.geometry}
        material={nodes.box_234.material}
        position={[42, -45.56, 21]}
        scale={[3.75, 1, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_14.geometry}
        material={nodes.box_14.material}
        position={[22.5, -30.88, -20.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_15.geometry}
        material={nodes.box_15.material}
        position={[22.5, -36.38, -25.5]}
        scale={[1.75, 0.25, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_16.geometry}
        material={nodes.box_16.material}
        position={[22.5, -25.88, -25.5]}
        scale={[1.75, 0.5, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_17.geometry}
        material={nodes.box_17.material}
        position={[22.5, -30.88, -30.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_28.geometry}
        material={nodes.box_28.material}
        position={[22.5, -3.88, -25.5]}
        scale={[1.75, 0.5, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_29.geometry}
        material={nodes.box_29.material}
        position={[22.5, -8.88, -30.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_30.geometry}
        material={nodes.box_30.material}
        position={[22.5, -8.88, -20.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_31.geometry}
        material={nodes.box_31.material}
        position={[22.5, -9.12, -25.5]}
        scale={[1.57, 0.23, 2.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_32.geometry}
        material={nodes.box_32.material}
        position={[22.5, -14.38, -25.5]}
        scale={[1.75, 0.25, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_33.geometry}
        material={nodes.box_33.material}
        position={[22.5, 13.24, -25.5]}
        scale={[1.75, 0.5, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_34.geometry}
        material={nodes.box_34.material}
        position={[22.5, 8.24, -30.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_35.geometry}
        material={nodes.box_35.material}
        position={[22.5, 8, -25.5]}
        scale={[1.57, 0.23, 2.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_36.geometry}
        material={nodes.box_36.material}
        position={[22.5, 2.74, -25.5]}
        scale={[1.75, 0.25, 2.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_47.geometry}
        material={nodes.box_47.material}
        position={[22.5, -31.12, -25.5]}
        scale={[1.57, 0.23, 2.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_52.geometry}
        material={nodes.box_52.material}
        position={[22.5, 8.24, -20.5]}
        scale={[1.75, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_59.geometry}
        material={nodes.box_59.material}
        position={[0, -12.34, -26.5]}
        scale={[11.97, 16.5, 10.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_60.geometry}
        material={nodes.box_60.material}
        position={[0, 21.92, -26.5]}
        scale={[13.23, 0.63, 11.34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_66.geometry}
        material={nodes.box_66.material}
        position={[14, 3.64, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_67.geometry}
        material={nodes.box_67.material}
        position={[10.4, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_69.geometry}
        material={nodes.box_69.material}
        position={[17.6, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_70.geometry}
        material={nodes.box_70.material}
        position={[14, 13.84, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_72.geometry}
        material={nodes.box_72.material}
        position={[-3.6, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_73.geometry}
        material={nodes.box_73.material}
        position={[0, 13.84, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_74.geometry}
        material={nodes.box_74.material}
        position={[3.6, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_75.geometry}
        material={nodes.box_75.material}
        position={[0, 3.64, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_76.geometry}
        material={nodes.box_76.material}
        position={[-14, 3.64, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_77.geometry}
        material={nodes.box_77.material}
        position={[-17.6, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_78.geometry}
        material={nodes.box_78.material}
        position={[-14, 13.84, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_79.geometry}
        material={nodes.box_79.material}
        position={[-10.4, 8.44, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_82.geometry}
        material={nodes.box_82.material}
        position={[-10.4, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_83.geometry}
        material={nodes.box_83.material}
        position={[-14, -3.16, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_84.geometry}
        material={nodes.box_84.material}
        position={[-17.6, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_85.geometry}
        material={nodes.box_85.material}
        position={[-14, -13.36, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_86.geometry}
        material={nodes.box_86.material}
        position={[0, -13.36, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_87.geometry}
        material={nodes.box_87.material}
        position={[3.6, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_88.geometry}
        material={nodes.box_88.material}
        position={[0, -3.16, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_89.geometry}
        material={nodes.box_89.material}
        position={[-3.6, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_91.geometry}
        material={nodes.box_91.material}
        position={[14, -3.16, -7.1]}
        scale={[2.1, 0.3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_92.geometry}
        material={nodes.box_92.material}
        position={[17.6, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_94.geometry}
        material={nodes.box_94.material}
        position={[10.4, -8.56, -7.1]}
        scale={[0.3, 3, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_95.geometry}
        material={nodes.box_95.material}
        position={[14, -13.56, -6.5]}
        scale={[2.7, 0.6, 1.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_101.geometry}
        material={nodes.box_101.material}
        position={[-13.5, -23.56, -7.1]}
        scale={[2.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_102.geometry}
        material={nodes.box_102.material}
        position={[-9.5, -30.56, -7.1]}
        scale={[0.25, 3.75, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_104.geometry}
        material={nodes.box_104.material}
        position={[-17.5, -30.56, -7.1]}
        scale={[0.25, 3.75, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_48.geometry}
        material={nodes.box_48.material}
        position={[22, -30.88, -25.5]}
        scale={[1.5, 2.5, 2.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_49.geometry}
        material={nodes.box_49.material}
        position={[22, -8.88, -25.5]}
        scale={[1.5, 2.5, 2.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_51.geometry}
        material={nodes.box_51.material}
        position={[22, 8.24, -25.5]}
        scale={[1.5, 2.5, 2.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_68.geometry}
        material={nodes.box_68.material}
        position={[14, 8.44, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_71.geometry}
        material={nodes.box_71.material}
        position={[0, 8.44, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_80.geometry}
        material={nodes.box_80.material}
        position={[-14, 8.44, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_81.geometry}
        material={nodes.box_81.material}
        position={[-14, -8.56, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_90.geometry}
        material={nodes.box_90.material}
        position={[0, -8.56, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_93.geometry}
        material={nodes.box_93.material}
        position={[14, -8.56, -7.7]}
        scale={[1.5, 2.4, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_97.geometry}
        material={nodes.box_97.material}
        position={[7.5, -25.26, -7.1]}
        scale={[5.75, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_98.geometry}
        material={nodes.box_98.material}
        position={[18.5, -30.26, -7.1]}
        scale={[0.25, 2.75, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_99.geometry}
        material={nodes.box_99.material}
        position={[7.5, -35.26, -7.1]}
        scale={[5.75, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_100.geometry}
        material={nodes.box_100.material}
        position={[-3.5, -30.26, -7.1]}
        scale={[0.25, 2.75, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_105.geometry}
        material={nodes.box_105.material}
        position={[-5.5, -36.06, -4.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_106.geometry}
        material={nodes.box_106.material}
        position={[-21.5, -36.06, -4.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_107.geometry}
        material={nodes.box_107.material}
        position={[-5, -34.56, -2]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.5, 0.25, 2.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_108.geometry}
        material={nodes.box_108.material}
        position={[-7, -34.56, 2]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_109.geometry}
        material={nodes.box_109.material}
        position={[-22, -34.56, -2]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.5, 0.25, 2.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_110.geometry}
        material={nodes.box_110.material}
        position={[-20, -34.56, 2]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1, 0.25, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_111.geometry}
        material={nodes.box_111.material}
        position={[-5.5, -36.06, -1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_112.geometry}
        material={nodes.box_112.material}
        position={[-5.5, -36.06, 1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_113.geometry}
        material={nodes.box_113.material}
        position={[-21.5, -36.06, 1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_114.geometry}
        material={nodes.box_114.material}
        position={[-8.5, -36.06, 1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_115.geometry}
        material={nodes.box_115.material}
        position={[-13.5, -43.56, 4.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2.25, 0.75, 1.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_116.geometry}
        material={nodes.box_116.material}
        position={[-13.5, -41.56, 3]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2.25, 0.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_117.geometry}
        material={nodes.box_117.material}
        position={[-13.5, -44.56, 9.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-2.25, 0.25, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_118.geometry}
        material={nodes.box_118.material}
        position={[-18.5, -36.06, 1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_119.geometry}
        material={nodes.box_119.material}
        position={[-13.5, -41.56, -2.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-4.25, 1.75, 2.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_120.geometry}
        material={nodes.box_120.material}
        position={[-21.5, -36.06, -1.5]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.25, 1, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_122.geometry}
        material={nodes.box_122.material}
        position={[6.5, 27.34, -32.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[2, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_123.geometry}
        material={nodes.box_123.material}
        position={[16.5, 27.34, -32.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[2, 1, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_124.geometry}
        material={nodes.box_124.material}
        position={[11.5, 27.34, -28]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.25, 1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_125.geometry}
        material={nodes.box_125.material}
        position={[11.5, 27.34, -37]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.25, 1, 3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_221.geometry}
        material={nodes.box_221.material}
        position={[60, -46.56, 38]}
        scale={[3.75, 0.5, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_222.geometry}
        material={nodes.box_222.material}
        position={[-50, -46.56, 38]}
        scale={[3.75, 0.5, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_223.geometry}
        material={nodes.box_223.material}
        position={[-22, -46.56, 38]}
        scale={[3.75, 0.5, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_224.geometry}
        material={nodes.box_224.material}
        position={[5, -46.56, 38]}
        scale={[3.75, 0.5, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_225.geometry}
        material={nodes.box_225.material}
        position={[32, -46.56, 38]}
        scale={[3.75, 0.5, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_58.geometry}
        material={nodes.box_58.material}
        position={[0, 37, -10]}
        scale={[7.25, 3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_61.geometry}
        material={nodes.box_61.material}
        position={[-22.68, 24.44, -26.5]}
        scale={[0.63, 1.89, 10.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_62.geometry}
        material={nodes.box_62.material}
        position={[0, 24.44, -45.4]}
        scale={[11.97, 1.89, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_63.geometry}
        material={nodes.box_63.material}
        position={[0, 24.44, -26.5]}
        scale={[11.97, 0.63, 10.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_64.geometry}
        material={nodes.box_64.material}
        position={[0, 24.44, -7.6]}
        scale={[11.97, 1.89, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_65.geometry}
        material={nodes.box_65.material}
        position={[22.68, 24.44, -26.5]}
        scale={[0.63, 1.89, 10.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_96.geometry}
        material={nodes.box_96.material}
        position={[7.5, -30.26, -7.7]}
        scale={[5.25, 2.25, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_103.geometry}
        material={nodes.box_103.material}
        position={[-13.5, -31.06, -7.7]}
        scale={[1.75, 3.5, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_121.geometry}
        material={nodes.box_121.material}
        position={[-10.5, 35.01, -26.47]}
        scale={[2.46, 0.11, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_126.geometry}
        material={nodes.box_126.material}
        position={[-13.52, 34.45, -30.5]}
        scale={[0.17, 0.17, 2.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_127.geometry}
        material={nodes.box_127.material}
        position={[-7.48, 34.45, -30.5]}
        scale={[0.17, 0.17, 2.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_128.geometry}
        material={nodes.box_128.material}
        position={[-14.42, 30.08, -34.08]}
        scale={[0.17, 2.38, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_129.geometry}
        material={nodes.box_129.material}
        position={[-14.42, 29.46, -30.5]}
        scale={[0.17, 0.17, 1.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_130.geometry}
        material={nodes.box_130.material}
        position={[-14.42, 30.08, -26.92]}
        scale={[0.17, 2.38, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_131.geometry}
        material={nodes.box_131.material}
        position={[-6.58, 29.46, -30.5]}
        scale={[0.17, 0.17, 1.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_132.geometry}
        material={nodes.box_132.material}
        position={[-6.58, 30.08, -26.92]}
        scale={[0.17, 2.38, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_133.geometry}
        material={nodes.box_133.material}
        position={[-10.5, 29.46, -26.92]}
        scale={[2.13, 0.17, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_134.geometry}
        material={nodes.box_134.material}
        position={[-10.5, 29.46, -34.08]}
        scale={[2.13, 0.17, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_135.geometry}
        material={nodes.box_135.material}
        position={[-6.58, 30.08, -34.08]}
        scale={[0.17, 2.38, 0.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_136.geometry}
        material={nodes.box_136.material}
        position={[-10.5, 35.01, -34.53]}
        scale={[2.46, 0.11, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_137.geometry}
        material={nodes.box_137.material}
        position={[-10.5, 35.01, -32.52]}
        scale={[2.46, 0.11, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_138.geometry}
        material={nodes.box_138.material}
        position={[-10.5, 35.01, -30.5]}
        scale={[2.46, 0.11, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_139.geometry}
        material={nodes.box_139.material}
        position={[-10.5, 35.01, -28.48]}
        scale={[2.46, 0.11, 0.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_153.geometry}
        material={nodes.box_153.material}
        position={[-67.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_154.geometry}
        material={nodes.box_154.material}
        position={[-67.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_155.geometry}
        material={nodes.box_155.material}
        position={[-67.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_156.geometry}
        material={nodes.box_156.material}
        position={[-61.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_157.geometry}
        material={nodes.box_157.material}
        position={[-55.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_158.geometry}
        material={nodes.box_158.material}
        position={[-67.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_159.geometry}
        material={nodes.box_159.material}
        position={[-61.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_160.geometry}
        material={nodes.box_160.material}
        position={[-47, -46.56, -30.5]}
        scale={[11.75, 0.5, 12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_161.geometry}
        material={nodes.box_161.material}
        position={[-61.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_162.geometry}
        material={nodes.box_162.material}
        position={[-55.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_163.geometry}
        material={nodes.box_163.material}
        position={[-55.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_164.geometry}
        material={nodes.box_164.material}
        position={[-55.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_165.geometry}
        material={nodes.box_165.material}
        position={[-49.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_166.geometry}
        material={nodes.box_166.material}
        position={[-49.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_167.geometry}
        material={nodes.box_167.material}
        position={[-43.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_168.geometry}
        material={nodes.box_168.material}
        position={[-43.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_169.geometry}
        material={nodes.box_169.material}
        position={[-31.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_170.geometry}
        material={nodes.box_170.material}
        position={[-43.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_171.geometry}
        material={nodes.box_171.material}
        position={[-49.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_172.geometry}
        material={nodes.box_172.material}
        position={[-37.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_174.geometry}
        material={nodes.box_174.material}
        position={[-43.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_175.geometry}
        material={nodes.box_175.material}
        position={[-37.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_177.geometry}
        material={nodes.box_177.material}
        position={[-31.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_178.geometry}
        material={nodes.box_178.material}
        position={[-26, -45.06, -45.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_179.geometry}
        material={nodes.box_179.material}
        position={[-49.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_180.geometry}
        material={nodes.box_180.material}
        position={[-61.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_181.geometry}
        material={nodes.box_181.material}
        position={[-26, -45.06, -9.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_182.geometry}
        material={nodes.box_182.material}
        position={[-37.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_183.geometry}
        material={nodes.box_183.material}
        position={[-31.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_185.geometry}
        material={nodes.box_185.material}
        position={[-26, -45.06, -21.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_186.geometry}
        material={nodes.box_186.material}
        position={[-37.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_187.geometry}
        material={nodes.box_187.material}
        position={[-31.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_188.geometry}
        material={nodes.box_188.material}
        position={[-26, -45.06, -33.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_275.geometry}
        material={nodes.box_275.material}
        position={[68, -45.06, -9.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_276.geometry}
        material={nodes.box_276.material}
        position={[56.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_277.geometry}
        material={nodes.box_277.material}
        position={[44.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_278.geometry}
        material={nodes.box_278.material}
        position={[32.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_279.geometry}
        material={nodes.box_279.material}
        position={[38.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_280.geometry}
        material={nodes.box_280.material}
        position={[44.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_281.geometry}
        material={nodes.box_281.material}
        position={[50.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_282.geometry}
        material={nodes.box_282.material}
        position={[62.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_283.geometry}
        material={nodes.box_283.material}
        position={[56.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_284.geometry}
        material={nodes.box_284.material}
        position={[68, -45.06, -21.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_285.geometry}
        material={nodes.box_285.material}
        position={[62.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_286.geometry}
        material={nodes.box_286.material}
        position={[50.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_287.geometry}
        material={nodes.box_287.material}
        position={[38.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_288.geometry}
        material={nodes.box_288.material}
        position={[32.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_289.geometry}
        material={nodes.box_289.material}
        position={[32.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_290.geometry}
        material={nodes.box_290.material}
        position={[38.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_291.geometry}
        material={nodes.box_291.material}
        position={[44.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_292.geometry}
        material={nodes.box_292.material}
        position={[50.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_293.geometry}
        material={nodes.box_293.material}
        position={[56.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_294.geometry}
        material={nodes.box_294.material}
        position={[68, -45.06, -33.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_295.geometry}
        material={nodes.box_295.material}
        position={[62.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_296.geometry}
        material={nodes.box_296.material}
        position={[68, -45.06, -45.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_297.geometry}
        material={nodes.box_297.material}
        position={[56.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_298.geometry}
        material={nodes.box_298.material}
        position={[62.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_299.geometry}
        material={nodes.box_299.material}
        position={[50.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_300.geometry}
        material={nodes.box_300.material}
        position={[44.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_301.geometry}
        material={nodes.box_301.material}
        position={[38.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_302.geometry}
        material={nodes.box_302.material}
        position={[32.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_303.geometry}
        material={nodes.box_303.material}
        position={[26.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_304.geometry}
        material={nodes.box_304.material}
        position={[20.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_305.geometry}
        material={nodes.box_305.material}
        position={[26.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_306.geometry}
        material={nodes.box_306.material}
        position={[14.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_307.geometry}
        material={nodes.box_307.material}
        position={[8.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_308.geometry}
        material={nodes.box_308.material}
        position={[-3.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_309.geometry}
        material={nodes.box_309.material}
        position={[2.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_310.geometry}
        material={nodes.box_310.material}
        position={[-21, -45.06, -51.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_311.geometry}
        material={nodes.box_311.material}
        position={[-15.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_312.geometry}
        material={nodes.box_312.material}
        position={[-9.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_313.geometry}
        material={nodes.box_313.material}
        position={[26.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_314.geometry}
        material={nodes.box_314.material}
        position={[26.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_173.geometry}
        material={nodes.box_173.material}
        position={[-31.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_184.geometry}
        material={nodes.box_184.material}
        position={[-26, -45.06, -15.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_189.geometry}
        material={nodes.box_189.material}
        position={[-26, -45.06, -51.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_190.geometry}
        material={nodes.box_190.material}
        position={[-26, -45.06, -39.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_191.geometry}
        material={nodes.box_191.material}
        position={[-26, -45.06, -27.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_192.geometry}
        material={nodes.box_192.material}
        position={[-43.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_193.geometry}
        material={nodes.box_193.material}
        position={[-55.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_194.geometry}
        material={nodes.box_194.material}
        position={[-67.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_195.geometry}
        material={nodes.box_195.material}
        position={[-49.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_196.geometry}
        material={nodes.box_196.material}
        position={[-61.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_197.geometry}
        material={nodes.box_197.material}
        position={[-67.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_198.geometry}
        material={nodes.box_198.material}
        position={[-55.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_199.geometry}
        material={nodes.box_199.material}
        position={[-43.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_200.geometry}
        material={nodes.box_200.material}
        position={[-49.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_201.geometry}
        material={nodes.box_201.material}
        position={[-61.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_202.geometry}
        material={nodes.box_202.material}
        position={[-67.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_203.geometry}
        material={nodes.box_203.material}
        position={[-55.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_204.geometry}
        material={nodes.box_204.material}
        position={[-43.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_205.geometry}
        material={nodes.box_205.material}
        position={[-49.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_206.geometry}
        material={nodes.box_206.material}
        position={[-61.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_207.geometry}
        material={nodes.box_207.material}
        position={[-67.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_208.geometry}
        material={nodes.box_208.material}
        position={[-61.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_209.geometry}
        material={nodes.box_209.material}
        position={[-55.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_210.geometry}
        material={nodes.box_210.material}
        position={[-49.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_211.geometry}
        material={nodes.box_211.material}
        position={[-43.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_212.geometry}
        material={nodes.box_212.material}
        position={[-37.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_213.geometry}
        material={nodes.box_213.material}
        position={[-37.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_214.geometry}
        material={nodes.box_214.material}
        position={[-37.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_215.geometry}
        material={nodes.box_215.material}
        position={[-37.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_216.geometry}
        material={nodes.box_216.material}
        position={[-31.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_217.geometry}
        material={nodes.box_217.material}
        position={[-31.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_218.geometry}
        material={nodes.box_218.material}
        position={[-31.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_235.geometry}
        material={nodes.box_235.material}
        position={[-21, -45.06, -45.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_236.geometry}
        material={nodes.box_236.material}
        position={[-15.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_237.geometry}
        material={nodes.box_237.material}
        position={[-9.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_238.geometry}
        material={nodes.box_238.material}
        position={[-3.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_239.geometry}
        material={nodes.box_239.material}
        position={[2.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_240.geometry}
        material={nodes.box_240.material}
        position={[8.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_241.geometry}
        material={nodes.box_241.material}
        position={[14.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_242.geometry}
        material={nodes.box_242.material}
        position={[20.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_243.geometry}
        material={nodes.box_243.material}
        position={[32.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_244.geometry}
        material={nodes.box_244.material}
        position={[44.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_245.geometry}
        material={nodes.box_245.material}
        position={[56.5, -45.06, -51.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_246.geometry}
        material={nodes.box_246.material}
        position={[68, -45.06, -51.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_247.geometry}
        material={nodes.box_247.material}
        position={[62.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_248.geometry}
        material={nodes.box_248.material}
        position={[50.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_249.geometry}
        material={nodes.box_249.material}
        position={[38.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_250.geometry}
        material={nodes.box_250.material}
        position={[26.5, -45.06, -45.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_251.geometry}
        material={nodes.box_251.material}
        position={[32.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_252.geometry}
        material={nodes.box_252.material}
        position={[44.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_253.geometry}
        material={nodes.box_253.material}
        position={[56.5, -45.06, -39.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_254.geometry}
        material={nodes.box_254.material}
        position={[68, -45.06, -39.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_255.geometry}
        material={nodes.box_255.material}
        position={[62.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_256.geometry}
        material={nodes.box_256.material}
        position={[50.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_257.geometry}
        material={nodes.box_257.material}
        position={[38.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_258.geometry}
        material={nodes.box_258.material}
        position={[26.5, -45.06, -33.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_259.geometry}
        material={nodes.box_259.material}
        position={[32.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_260.geometry}
        material={nodes.box_260.material}
        position={[44.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_261.geometry}
        material={nodes.box_261.material}
        position={[56.5, -45.06, -27.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_262.geometry}
        material={nodes.box_262.material}
        position={[68, -45.06, -27.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_263.geometry}
        material={nodes.box_263.material}
        position={[62.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_264.geometry}
        material={nodes.box_264.material}
        position={[50.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_265.geometry}
        material={nodes.box_265.material}
        position={[38.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_266.geometry}
        material={nodes.box_266.material}
        position={[26.5, -45.06, -21.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_267.geometry}
        material={nodes.box_267.material}
        position={[32.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_268.geometry}
        material={nodes.box_268.material}
        position={[44.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_269.geometry}
        material={nodes.box_269.material}
        position={[56.5, -45.06, -15.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_270.geometry}
        material={nodes.box_270.material}
        position={[68, -45.06, -15.5]}
        scale={[1.25, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_271.geometry}
        material={nodes.box_271.material}
        position={[62.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_272.geometry}
        material={nodes.box_272.material}
        position={[50.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_273.geometry}
        material={nodes.box_273.material}
        position={[26.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_274.geometry}
        material={nodes.box_274.material}
        position={[38.5, -45.06, -9.5]}
        scale={[1.5, 0.25, 1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder.geometry}
        material={nodes.quarterCylinder.material}
        position={[15.9, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_1.geometry}
        material={nodes.quarterCylinder_1.material}
        position={[13.5, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_2.geometry}
        material={nodes.quarterCylinder_2.material}
        position={[11.1, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_3.geometry}
        material={nodes.quarterCylinder_3.material}
        position={[8.7, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_4.geometry}
        material={nodes.quarterCylinder_4.material}
        position={[6.3, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_5.geometry}
        material={nodes.quarterCylinder_5.material}
        position={[3.9, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_6.geometry}
        material={nodes.quarterCylinder_6.material}
        position={[1.5, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_7.geometry}
        material={nodes.quarterCylinder_7.material}
        position={[-0.9, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_8.geometry}
        material={nodes.quarterCylinder_8.material}
        position={[-3.3, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_9.geometry}
        material={nodes.quarterCylinder_9.material}
        position={[18.3, -20.56, -2.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[4.05, 3.24, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder.geometry}
        material={nodes.cylinder.material}
        position={[-10.5, 39.03, -30.5]}
        scale={[1.84, 1.9, 1.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_1.geometry}
        material={nodes.cylinder_1.material}
        position={[-10.5, 41.28, -30.5]}
        scale={[2.02, 0.46, 2.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_4.geometry}
        material={nodes.cylinder_4.material}
        position={[-10.5, 39.03, -30.5]}
        scale={[2.02, 0.46, 2.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_5.geometry}
        material={nodes.cylinder_5.material}
        position={[-10.5, 36.79, -30.5]}
        scale={[2.02, 0.46, 2.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_2.geometry}
        material={nodes.cylinder_2.material}
        position={[11.5, 27.94, -32.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cylinder_3.geometry}
        material={nodes.cylinder_3.material}
        position={[11.5, 27.34, -32.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[2, 0.5, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cone.geometry}
        material={nodes.cone.material}
        position={[-10.5, 45.14, -30.5]}
        scale={[2.42, 1.21, 2.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cone_1.geometry}
        material={nodes.cone_1.material}
        position={[-47.57, -33.01, -28.96]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.2, 6.9, 1.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cone_2.geometry}
        material={nodes.cone_2.material}
        position={[47.5, -33.5, -27.5]}
        scale={[1, 5.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hemisphere.geometry}
        material={nodes.hemisphere.material}
        position={[11.5, 28.74, -32.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.circleWedge.geometry}
        material={nodes.circleWedge.material}
        position={[9.5, 27.34, -30.5]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.circleWedge_1.geometry}
        material={nodes.circleWedge_1.material}
        position={[9.5, 27.34, -34.5]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.circleWedge_2.geometry}
        material={nodes.circleWedge_2.material}
        position={[13.5, 27.34, -34.5]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.circleWedge_3.geometry}
        material={nodes.circleWedge_3.material}
        position={[13.5, 27.34, -30.5]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_10.geometry}
        material={nodes.quarterCylinder_10.material}
        position={[14.5, 26.44, -26.5]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1.43, 1.43, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.quarterCylinder_11.geometry}
        material={nodes.quarterCylinder_11.material}
        position={[8.5, 26.44, -26.5]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1.43, 1.43, 0.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron.geometry}
        material={nodes.icosahedron.material}
        position={[49.5, -30.5, -26.5]}
        scale={2.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_1.geometry}
        material={nodes.icosahedron_1.material}
        position={[47.5, -24.5, -35.5]}
        scale={2.98}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_2.geometry}
        material={nodes.icosahedron_2.material}
        position={[51.5, -21.5, -25.5]}
        scale={2.24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_3.geometry}
        material={nodes.icosahedron_3.material}
        position={[42.5, -22.5, -28.5]}
        scale={3.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_4.geometry}
        material={nodes.icosahedron_4.material}
        position={[54.5, -28.5, -33.5]}
        scale={3.11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_5.geometry}
        material={nodes.icosahedron_5.material}
        position={[43.5, -28.5, -21.5]}
        scale={3.11}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_6.geometry}
        material={nodes.icosahedron_6.material}
        position={[46.5, -26.5, -29.5]}
        scale={5.18}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_7.geometry}
        material={nodes.icosahedron_7.material}
        position={[-46.17, -24.61, -30.16]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={6.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_8.geometry}
        material={nodes.icosahedron_8.material}
        position={[-54.5, -24.5, -33.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={3.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_9.geometry}
        material={nodes.icosahedron_9.material}
        position={[-40.5, -27.01, -24.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={3.73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_10.geometry}
        material={nodes.icosahedron_10.material}
        position={[-47.37, -19.81, -34.96]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_11.geometry}
        material={nodes.icosahedron_11.material}
        position={[-48.5, -18.61, -24.16]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2.69}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_12.geometry}
        material={nodes.icosahedron_12.material}
        position={[-40.5, -22.21, -28.96]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={3.58}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icosahedron_13.geometry}
        material={nodes.icosahedron_13.material}
        position={[-51.5, -27.5, -26.56]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.03}
      />
    </group>
  );
}

useGLTF.preload("/home.glb");
